# Generated by Django 5.1.1 on 2024-11-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('CPF', models.CharField(max_length=14)),
                ('RG', models.CharField(max_length=12)),
                ('admissao', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=80)),
                ('salario', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Exemplo Empresa 1 ----------- CNPJ 11.111.111/1111-11',
            },
        ),
        migrations.CreateModel(
            name='empresa3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('CPF', models.CharField(max_length=14)),
                ('RG', models.CharField(max_length=12)),
                ('admissao', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=80)),
                ('salario', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Exemplo Empresa 2 ----------- CNPJ 22.222.222/2222-22',
            },
        ),
        migrations.CreateModel(
            name='geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('CPF', models.CharField(max_length=14)),
                ('RG', models.CharField(max_length=12)),
                ('admissao', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=80)),
                ('salario', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Tabelas Gerais',
            },
        ),
    ]
