# Generated by Django 5.1.1 on 2024-11-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('CPF', models.CharField(max_length=14)),
                ('RG', models.CharField(max_length=12)),
                ('admissao', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=80)),
                ('salario', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='empresa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('CPF', models.CharField(max_length=14)),
                ('RG', models.CharField(max_length=12)),
                ('admissao', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=80)),
                ('salario', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='empresa3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('CPF', models.CharField(max_length=14)),
                ('RG', models.CharField(max_length=12)),
                ('admissao', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=80)),
                ('salario', models.CharField()),
            ],
        ),
    ]
