-- Table: public.admin_interface_theme

-- DROP TABLE IF EXISTS public.admin_interface_theme;

CREATE TABLE IF NOT EXISTS public.admin_interface_theme
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    active boolean NOT NULL,
    title character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title_visible boolean NOT NULL,
    logo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    logo_visible boolean NOT NULL,
    css_header_background_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    title_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_header_text_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_header_link_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_header_link_hover_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_module_background_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_module_text_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_module_link_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_module_link_hover_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_module_rounded_corners boolean NOT NULL,
    css_generic_link_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_generic_link_hover_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_save_button_background_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_save_button_background_hover_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_save_button_text_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_delete_button_background_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_delete_button_background_hover_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_delete_button_text_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    list_filter_dropdown boolean NOT NULL,
    related_modal_active boolean NOT NULL,
    related_modal_background_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    related_modal_rounded_corners boolean NOT NULL,
    logo_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    recent_actions_visible boolean NOT NULL,
    favicon character varying(100) COLLATE pg_catalog."default" NOT NULL,
    related_modal_background_opacity character varying(5) COLLATE pg_catalog."default" NOT NULL,
    env_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    env_visible_in_header boolean NOT NULL,
    env_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    env_visible_in_favicon boolean NOT NULL,
    related_modal_close_button_visible boolean NOT NULL,
    language_chooser_active boolean NOT NULL,
    language_chooser_display character varying(10) COLLATE pg_catalog."default" NOT NULL,
    list_filter_sticky boolean NOT NULL,
    form_pagination_sticky boolean NOT NULL,
    form_submit_sticky boolean NOT NULL,
    css_module_background_selected_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    css_module_link_selected_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    logo_max_height smallint NOT NULL,
    logo_max_width smallint NOT NULL,
    foldable_apps boolean NOT NULL,
    language_chooser_control character varying(20) COLLATE pg_catalog."default" NOT NULL,
    list_filter_highlight boolean NOT NULL,
    list_filter_removal_links boolean NOT NULL,
    show_fieldsets_as_tabs boolean NOT NULL,
    show_inlines_as_tabs boolean NOT NULL,
    css_generic_link_active_color character varying(10) COLLATE pg_catalog."default" NOT NULL,
    collapsible_stacked_inlines boolean NOT NULL,
    collapsible_stacked_inlines_collapsed boolean NOT NULL,
    collapsible_tabular_inlines boolean NOT NULL,
    collapsible_tabular_inlines_collapsed boolean NOT NULL,
    CONSTRAINT admin_interface_theme_pkey PRIMARY KEY (id),
    CONSTRAINT admin_interface_theme_name_30bda70f_uniq UNIQUE (name),
    CONSTRAINT admin_interface_theme_logo_max_height_check CHECK (logo_max_height >= 0),
    CONSTRAINT admin_interface_theme_logo_max_width_check CHECK (logo_max_width >= 0)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.admin_interface_theme
    OWNER to postgres;
-- Index: admin_interface_theme_name_30bda70f_like

-- DROP INDEX IF EXISTS public.admin_interface_theme_name_30bda70f_like;

CREATE INDEX IF NOT EXISTS admin_interface_theme_name_30bda70f_like
    ON public.admin_interface_theme USING btree
    (name COLLATE pg_catalog."default" varchar_pattern_ops ASC NULLS LAST)
    TABLESPACE pg_default;